set(command "C:/Program Files/CMake/bin/cmake.exe;-P;F:/Study/Homework/HW3/swig-download/SWIG_project-prefix/src/SWIG_project-stamp/download-SWIG_project.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "C:/Program Files/CMake/bin/cmake.exe;-P;F:/Study/Homework/HW3/swig-download/SWIG_project-prefix/src/SWIG_project-stamp/verify-SWIG_project.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "C:/Program Files/CMake/bin/cmake.exe;-P;F:/Study/Homework/HW3/swig-download/SWIG_project-prefix/src/SWIG_project-stamp/extract-SWIG_project.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
